---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    open-pull-requests-limit: 2
    schedule:
      interval: "daily"
      time: "11:00"
    labels:
      - "ignore-for-release"
    commit-message:
      prefix: chore(ci)

  - package-ecosystem: gomod
    directory: /
    open-pull-requests-limit: 2
    schedule:
      interval: "daily"
      time: "23:00"
    labels:
      - "dependencies"
    commit-message:
      prefix: chore
      include: "scope"
    groups:
      golang-org-x:
        patterns:
          - "golang.org/x/*"

